<?php
$name = '';
$id = '';
if (!empty($this->zoneconfig['conf']['name']))
    $name = $this->zoneconfig['conf']['name'];
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];

?>
<div class="modal-content">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons pencil" data-toggle="tab" aria-expanded="true"><i></i> <?php echo sprintf($this->translate('tr_melis_cms_prospects_theme_items_edit'), !empty($this->code) ? strtoupper($this->code) : null); ?></a></li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-pane active" id="<?= $id ?>">
                        <div class="row">
                            <div class="col-xs-12 col-md-4">
                                <div class="product-text-tab-container">
                                    <ul class="nav-tabs product-text-tab">
                                        <?php foreach($this->languages as $idx => $lang) {?>
                                            <li class="">
                                                <a class="clearfix" data-toggle="tab" href="#<?= $lang['lang_cms_name']; ?>-log-type-details" aria-expanded="false">
                                                    <span><?= $lang['lang_cms_name']; ?></span>
                                                    <?php
                                                    $img = $lang['lang_cms_locale'];
                                                    echo '<span class="float-right"><img src="/MelisCms/images/lang-flags/'.$img.'.png" class="imgDisplay float-right"/></span>';
                                                    ?>
                                                </a>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-8">
                                <div class="tab-content">
                                    <?php foreach ($this->languages as $idx => $lang) { ?>
                                        <div id="<?= $lang['lang_cms_name']; ?>-log-type-details" class="tab-pane product-text-tab-content">
                                            <div class="bg-white">
                                                <h4 class=""><i class="fa fa-language" aria-hidden="true"></i> <?= $lang['lang_cms_name']; ?></h4>
                                            </div>
                                            <?php
                                            $form = clone $this->form;
                                            foreach($this->data as $item){
                                                
                                                if($item['item_trans_lang_id'] == $lang['lang_cms_id']){
                                                    $form->setData((array)$item);
                                                }
                                            }
                                            $form->setData(array('item_trans_theme_item_id' => $this->itemId));
                                            $form->setData(array('item_trans_lang_id' => $lang['lang_cms_id']));
                                            $form->prepare();
                                            echo $this->form()->openTag($form);
                                            echo $this->melisFieldCollection($form);
                                            echo $this->form()->closeTag();
                                            ?>
                                        </div>
                                    <?php }?>
                                </div>
                            </div>
                        </div>
                        <div class="footer-modal d-flex flex-row justify-content-between">
                            <button data-dismiss="modal" class="btn btn-danger"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscore_common_close')?></button>
                            <button class="btn btn-success" id="btn-save-theme-items"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscore_tool_gen_save'); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
