-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 20:23:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_prospects_themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_prospects_themes` (
  `pros_theme_id` INT NOT NULL AUTO_INCREMENT,
  `pros_theme_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pros_theme_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_prospects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_prospects` (
  `pros_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pros_site_id` INT(11) NULL,
  `pros_type` VARCHAR(255) NULL,
  `pros_theme` INT(11) NULL,
  `pros_name` VARCHAR(255) NULL,
  `pros_email` VARCHAR(150) NULL,
  `pros_telephone` VARCHAR(20) NULL,
  `pros_message` TEXT NULL,
  `pros_company` VARCHAR(45) NULL,
  `pros_country` VARCHAR(45) NULL,
  `pros_contact_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pros_id`),
  INDEX `fk_theme_id_idx` (`pros_theme` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `melis_cms_prospects_theme_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_prospects_theme_items` (
  `pros_theme_item_id` INT NOT NULL AUTO_INCREMENT,
  `pros_theme_id` INT NOT NULL,
  PRIMARY KEY (`pros_theme_item_id`),
  INDEX `fk_pros_subj_id_idx` (`pros_theme_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_prospects_theme_items_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_prospects_theme_items_trans` (
  `item_trans_id` INT NOT NULL AUTO_INCREMENT,
  `item_trans_text` VARCHAR(255) NOT NULL,
  `item_trans_lang_id` INT NOT NULL,
  `item_trans_theme_item_id` INT NOT NULL,
  PRIMARY KEY (`item_trans_id`),
  INDEX `fk_melis_cms_prospects_theme_items_trans_melis_cms_prospect_idx` (`item_trans_theme_item_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
