-- MySQL Script generated by MySQL Workbench
-- 09/07/16 11:09:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_prospects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_prospects` (
  `pros_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `pros_site_id` INT(11) NOT NULL COMMENT '',
  `pros_type` VARCHAR(255) NOT NULL COMMENT '',
  `pros_theme` VARCHAR(255) NOT NULL COMMENT '',
  `pros_name` VARCHAR(255) NOT NULL COMMENT '',
  `pros_email` VARCHAR(150) NOT NULL COMMENT '',
  `pros_telephone` VARCHAR(20) NOT NULL COMMENT '',
  `pros_societe` VARCHAR(255) NOT NULL COMMENT '',
  `pros_message` TEXT NOT NULL COMMENT '',
  `pros_contact_date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`pros_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
