<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<div class="widget-parent" <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>'>
	<div class="widget-head">
		<div class="btn-group pull-right btn-group-xs">
			<a href="#chart-simple-lines" class="btn btn-default active" data-toggle="tab"><i class="fa fa-bars"></i></a>
			<a href="#chart-simple-bars" class="btn btn-default" data-toggle="tab"><i class="fa fa-bar-chart-o"></i></a>
			<a class="btn btn-default melis-refreshZone" data-toggle="tab"><i class="fa fa-refresh"></i></a>
		</div>
		<h3 class="heading"><i class="icon-stocks-up"></i> <?= $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics'); ?></h3>
	</div>
	<div class="widget-body padding-none">
		<div class="row row-merge">
			<div class="col-sm-12 bg-white">
				<div class="innerAll">
					<div class="tab-content">
						<div class="tab-pane active" id="chart-simple-lines">
							<div class="btn-group pull-right" data-toggle="buttons">
                              	<label class="btn btn-default btn-sm active">
                                	<input type="radio" class="dashchartline" name="dashchartline" value="daily"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_daily')?>
                              	</label>
                              	<label class="btn btn-default btn-sm">
                                	<input type="radio" class="dashchartline" name="dashchartline" value="monthly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_monthly')?>
                              	</label>
                              	<label class="btn btn-default btn-sm">
                                	<input type="radio" class="dashchartline" name="dashchartline" value="yearly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_yearly')?>
                              	</label>
                            </div>
                            <div class="separator bottom"></div>
							<!-- Simple Chart -->
			            	<div id="chart_simple" class="flotchart-holder"></div>
						</div>
						<div class="tab-pane" id="chart-simple-bars">
							<div class="btn-group pull-right" data-toggle="buttons">
                              	<label class="btn btn-default btn-sm active">
                                	<input type="radio" class="dashchartbar" name="dashchartbar" value="daily"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_daily')?>
                              	</label>
                              	<label class="btn btn-default btn-sm">
                                	<input type="radio" class="dashchartbar" name="dashchartbar" value="monthly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_monthly')?>
                              	</label>
                              	<label class="btn btn-default btn-sm">
                                	<input type="radio" class="dashchartbar" name="dashchartbar" value="yearly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_yearly')?>
                              	</label>
                            </div>
                            <div class="separator bottom"></div>
							<!-- Simple Chart -->
			    			<div id="chart_simple_bars" class="flotchart-holder"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row row-merge">
			<div class="col-sm-3 bg-white">
				<div class="text-center innerAll border-bottom">
					<div class="separator bottom"></div>
					<i class="icon-graph-up-1 fa-4x text-primary"></i>
					<div class="separator bottom"></div>
					<p class="lead"><span class="text-large text-regular"><?php echo $this->numPropects ?></span> <span class="text-primary dashboard-prospects-label"><?php echo $this->translate('tr_melistoolprospects_tool_prospects') ?> </span></p>
				</div>
			</div>
			<div class="col-sm-9 bg-white">
    			<div class="overflow-x ">
    				<table class="table table-condensed border-top margin-none pros-dash-tbl">
    					<!-- Table heading -->
    					<thead class="bg-primary">
    						<tr>
    							<th class="center"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_id')?></th>
    							<th><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_name')?></th>
    							<th><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_email')?></th>
    							<th><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_date')?></th>
    						</tr>
    					</thead>
    					<!-- // Table heading END -->
    					<!-- Table body -->
    					<tbody>
    						<?php if (!empty($this->recentPropects)) :?>
    						
        						<?php $recentData = $this->recentPropects ?>
        						<!-- Table row -->
        						<?php for($i = 0; $i < count($recentData); $i++){ ?>
            						<tr>
            							<td class="center"><?php echo $recentData[$i]['pros_id']?> </td>
            							<td><div class="pros-dash-lbl"><?php echo $this->escapeHtml($recentData[$i]['pros_name']); ?></div></td>
            							<td><div class="pros-dash-lbl"><?php echo $this->escapeHtml($recentData[$i]['pros_email']); ?></div></td>
            							<td><?php echo date($this->dateFormat, strtotime($recentData[$i]['pros_contact_date']))?></td>
            						</tr>
        						<?php } ?>
    						<?php else: ?>
    							<tr>
        							<td class="center" colspan="3">No Data</td>
            					</tr>
    						<?php endif;?>
    						<!-- // Table row END -->
    					</tbody>
    					<!-- // Table body END -->
    				</table>
    				<!-- // Table END -->
    				
    			</div>
			</div>
		</div>
	</div>
</div>
