<?php if ($this->toolIsAccessible): ?>
<div class="widget widget-tabs widget-tabs-responsive">
    <!-- Tabs Heading -->
    <div class="widget-head">
        <ul class="nav nav-tabs">
            <li class="nav-item active">
            	<a class="glyphicons stats nav-link active" href="#chart-simple-lines-<?php echo $this->pluginConfig['plugin_id']?>" data-bs-toggle="tab"><i></i></a>
            </li>
            <li class="nav-item">
            	<a class="glyphicons charts chart-simple-lines-tab nav-link" href="#chart-simple-bars-<?php echo $this->pluginConfig['plugin_id']?>" data-bs-toggle="tab"><i></i></a>
            </li>
        </ul>
    </div>
    <!-- // Tabs Heading END -->
</div>


<div class="row row-merge">
	<div class="col-sm-12 bg-white">
		<div class="innerAll">
			<div class="tab-content">
				<div class="tab-pane active" id="chart-simple-lines-<?php echo $this->pluginConfig['plugin_id']?>">
					<div class="btn-group float-right" data-bs-toggle="buttons" role="group">
						<!-- active -->
						<input type="radio" class="cms-pros-dash-chart-line btn-check" id="chart-simple-lines-daily" name="cms-pros-dash-chart-line" value="daily" autocomplete="off" checked>
                      	<label class="btn btn-default btn-sm" for="chart-simple-lines-daily"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_daily')?></label>

						<input type="radio" class="cms-pros-dash-chart-line btn-check" id="chart-simple-lines-monthly" name="cms-pros-dash-chart-line" value="monthly" autocomplete="off">
                      	<label class="btn btn-default btn-sm" for="chart-simple-lines-monthly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_monthly')?></label>

						<input type="radio" class="cms-pros-dash-chart-line btn-check" id="chart-simple-lines-yearly" name="cms-pros-dash-chart-line" value="yearly" autocomplete="off">
                      	<label class="btn btn-default btn-sm" for="chart-simple-lines-yearly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_yearly')?></label>
                    </div>
                    <div class="separator bottom"></div>
	            	<div class="flotchart-holder cms-pros-dash-chart-line-graph" id="cms-pros-dash-chart-line-graph-<?php echo $this->pluginConfig['plugin_id']?>"></div>
				</div>
				<div class="tab-pane" id="chart-simple-bars-<?php echo $this->pluginConfig['plugin_id']?>">
					<div class="btn-group float-right" data-bs-toggle="buttons" role="group">
						<!-- active -->
						<input type="radio" class="cms-pros-dash-chart-bar btn-check" id="chart-simple-bars-daily" name="cms-pros-dash-chart-bar" value="daily" autocomplete="off" checked>
                      	<label class="btn btn-default btn-sm" for="chart-simple-bars-daily"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_daily')?></label>

						<input type="radio" class="cms-pros-dash-chart-bar btn-check" id="chart-simple-bars-monthly" name="cms-pros-dash-chart-bar" value="monthly" autocomplete="off">
                      	<label class="btn btn-default btn-sm" for="chart-simple-bars-monthly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_monthly')?></label>

						<input type="radio" class="cms-pros-dash-chart-bar btn-check" id="chart-simple-bars-yearly" name="cms-pros-dash-chart-bar" value="yearly" autocomplete="off">
                      	<label class="btn btn-default btn-sm" for="chart-simple-bars-yearly"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_yearly')?></label>
                    </div>
                    <div class="separator bottom"></div>
	    			<div class="flotchart-holder cms-pros-dash-chart-bar-graph" id="cms-pros-dash-chart-bar-graph-<?php echo $this->pluginConfig['plugin_id']?>"></div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row row-merge">
	<div class="col-sm-3 bg-white">
		<div class="text-center innerAll border-bottom">
			<div class="separator bottom"></div>
			<i class="icon-graph-up-1 fa-4x text-primary"></i>
			<div class="separator bottom"></div>
			<p class="lead"><span class="text-large text-regular"><?php echo $this->numPropects ?></span> <span class="text-primary dashboard-prospects-label"><?php echo $this->translate('tr_melistoolprospects_tool_prospects') ?> </span></p>
		</div>
	</div>
	<div class="col-sm-9 bg-white">
		<div class="overflow-x ">
			<table class="table table-condensed border-top margin-none pros-dash-tbl">
				<!-- Table heading -->
				<thead class="bg-primary">
					<tr>
						<th class="center"><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_id')?></th>
						<th><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_name')?></th>
						<th><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_email')?></th>
						<th><?php echo $this->translate('tr_melistoolprospects_dashboard_Prospects Statistics_date')?></th>
					</tr>
				</thead>
				<!-- // Table heading END -->
				<!-- Table body -->
				<tbody>
					<?php if (!empty($this->recentPropects)) :?>

						<?php $recentData = $this->recentPropects ?>
						<!-- Table row -->
						<?php for($i = 0; $i < count($recentData); $i++){ ?>
    						<tr>
    							<td class="center"><?php echo $recentData[$i]['pros_id']?> </td>
    							<td><div class="pros-dash-lbl"><?php echo $this->escapeHtml($recentData[$i]['pros_name']); ?></div></td>
    							<td><div class="pros-dash-lbl"><?php echo $this->escapeHtml($recentData[$i]['pros_email']); ?></div></td>
    							<td><?php echo date($this->dateFormat, strtotime($recentData[$i]['pros_contact_date']))?></td>
    						</tr>
						<?php } ?>
					<?php else: ?>
						<tr>
							<td class="center" colspan="3">No Data</td>
    					</tr>
					<?php endif;?>
					<!-- // Table row END -->
				</tbody>
				<!-- // Table body END -->
			</table>
			<!-- // Table END -->

		</div>
	</div>
</div>
<?php else: ?>
    <div class="no-rights-container">
        <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_rights'); ?></span>
    </div>
<?php endif; ?>